version: '3.7'
services:
  botpress:
    build: .
    volumes:
      - botpress-data:/botpress/data
      - ./data/bots:/botpress/data/bots
      - ./data/global:/botpress/data/global
    ports:
      - "3000:3000"

volumes:
  botpress-data:
