version: '3.7'
services:
  buscador:
    image: ayudantevirtual/integracion-moodle:latest
    env_file:
      - .env.buscador

  postgres:
    image: postgres:12.4-alpine
    env_file:
      - .env.postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  botpress:
    image: ayudantevirtual/ayudante-virtual:latest
    env_file:
      - .env.botpress
    depends_on:
      - buscador
      - postgres
    volumes:
      - botpress-data:/botpress/data/bots/ayudante-virtual/config

  nginx:
    build: 'nginx'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - botpress

volumes:
  botpress-data:
  postgres-data:
