version: '3.7'
services:
  buscador:
    image: 'ayudantevirtual/integracion-moodle:latest'
    env_file:
      - .env.buscador

  botpress:
    build: .
    volumes:
      - botpress-data:/botpress/data
      - ./data/bots:/botpress/data/bots
      - ./data/global:/botpress/data/global
    ports:
      - "3000:3000"

volumes:
  botpress-data:
