version: '3.7'
services:
  buscador:
    image: ayudantevirtual/integracion-moodle:latest
    env_file:
      - .env.buscador

  postgres:
    image: postgres:12.4-alpine
    env_file:
      - .env.postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  botpress:
    image: ayudantevirtual/ayudante-virtual:latest
    env_file:
      - .env.botpress
    depends_on:
      - buscador
      - postgres
    volumes:
      - ./config/channel-slack-av.json:/botpress/data/bots/ayudante-virtual/config/channel-slack-av.json
      - ./config/workspaces.json:/botpress/data/global/workspaces.json
      - ./config/botpress.config.json:/botpress/data/global/botpress.config.json

  nginx:
    build: 'nginx'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - botpress

volumes:
  postgres-data:
